# Generated by Django 4.1.7 on 2023-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_auto_20230402_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(
                blank=True, related_name="titles", to="reviews.genre"
            ),
        ),
    ]
